/**
 * UI string translations for non-game-data text across the site.
 * Every key MUST have an "eng" entry — that's the fallback.
 */

const UI: Record<string, Record<string, string>> = {
  // Tabs
  "Overview":        { eng: "Overview", deu: "Übersicht", esp: "Resumen", fra: "Aperçu", ita: "Panoramica", jpn: "概要", kor: "개요", pol: "Przegląd", ptb: "Visão geral", rus: "Обзор", spa: "Resumen", tha: "ภาพรวม", tur: "Genel Bakış", zhs: "概览" },
  "Details":         { eng: "Details", deu: "Details", esp: "Detalles", fra: "Détails", ita: "Dettagli", jpn: "詳細", kor: "상세", pol: "Szczegóły", ptb: "Detalhes", rus: "Детали", spa: "Detalles", tha: "รายละเอียด", tur: "Detaylar", zhs: "详情" },
  "Info":            { eng: "Info", deu: "Info", esp: "Info", fra: "Info", ita: "Info", jpn: "情報", kor: "정보", pol: "Info", ptb: "Info", rus: "Инфо", spa: "Info", tha: "ข้อมูล", tur: "Bilgi", zhs: "信息" },

  // Navigation
  "Back to":         { eng: "Back to", deu: "Zurück zu", esp: "Volver a", fra: "Retour à", ita: "Torna a", jpn: "戻る：", kor: "돌아가기:", pol: "Powrót do", ptb: "Voltar para", rus: "Назад к", spa: "Volver a", tha: "กลับไป", tur: "Geri dön:", zhs: "返回" },
  "Home":            { eng: "Home", deu: "Startseite", esp: "Inicio", fra: "Accueil", ita: "Home", jpn: "ホーム", kor: "홈", pol: "Strona główna", ptb: "Início", rus: "Главная", spa: "Inicio", tha: "หน้าแรก", tur: "Ana Sayfa", zhs: "首页" },

  // Search & filters
  "Search...":       { eng: "Search...", deu: "Suchen...", esp: "Buscar...", fra: "Rechercher...", ita: "Cerca...", jpn: "検索...", kor: "검색...", pol: "Szukaj...", ptb: "Pesquisar...", rus: "Поиск...", spa: "Buscar...", tha: "ค้นหา...", tur: "Ara...", zhs: "搜索..." },
  "All Colors":      { eng: "All Colors", deu: "Alle Farben", esp: "Todos los colores", fra: "Toutes les couleurs", ita: "Tutti i colori", jpn: "すべての色", kor: "모든 색상", pol: "Wszystkie kolory", ptb: "Todas as cores", rus: "Все цвета", spa: "Todos los colores", tha: "ทุกสี", tur: "Tüm Renkler", zhs: "所有颜色" },
  "All Types":       { eng: "All Types", deu: "Alle Typen", esp: "Todos los tipos", fra: "Tous les types", ita: "Tutti i tipi", jpn: "すべてのタイプ", kor: "모든 유형", pol: "Wszystkie typy", ptb: "Todos os tipos", rus: "Все типы", spa: "Todos los tipos", tha: "ทุกประเภท", tur: "Tüm Türler", zhs: "所有类型" },
  "All Rarities":    { eng: "All Rarities", deu: "Alle Seltenheiten", esp: "Todas las rarezas", fra: "Toutes les raretés", ita: "Tutte le rarità", jpn: "すべてのレアリティ", kor: "모든 희귀도", pol: "Wszystkie rzadkości", ptb: "Todas as raridades", rus: "Все редкости", spa: "Todas las rarezas", tha: "ทุกความหายาก", tur: "Tüm Nadirlikler", zhs: "所有稀有度" },
  "All Keywords":    { eng: "All Keywords", deu: "Alle Schlüsselwörter", esp: "Todas las palabras clave", fra: "Tous les mots-clés", ita: "Tutte le parole chiave", jpn: "すべてのキーワード", kor: "모든 키워드", pol: "Wszystkie słowa kluczowe", ptb: "Todas as palavras-chave", rus: "Все ключевые слова", spa: "Todas las palabras clave", tha: "คีย์เวิร์ดทั้งหมด", tur: "Tüm Anahtar Kelimeler", zhs: "所有关键词" },
  "All Pools":       { eng: "All Pools", deu: "Alle Pools", esp: "Todos los grupos", fra: "Tous les groupes", ita: "Tutti i gruppi", jpn: "すべてのプール", kor: "모든 풀", pol: "Wszystkie pule", ptb: "Todos os grupos", rus: "Все группы", spa: "Todos los grupos", tha: "ทุกกลุ่ม", tur: "Tüm Havuzlar", zhs: "所有池" },
  "All Characters":  { eng: "All Characters", deu: "Alle Charaktere", esp: "Todos los personajes", fra: "Tous les personnages", ita: "Tutti i personaggi", jpn: "すべてのキャラクター", kor: "모든 캐릭터", pol: "Wszystkie postacie", ptb: "Todos os personagens", rus: "Все персонажи", spa: "Todos los personajes", tha: "ตัวละครทั้งหมด", tur: "Tüm Karakterler", zhs: "所有角色" },
  "results":         { eng: "results", deu: "Ergebnisse", esp: "resultados", fra: "résultats", ita: "risultati", jpn: "件", kor: "결과", pol: "wyników", ptb: "resultados", rus: "результатов", spa: "resultados", tha: "ผลลัพธ์", tur: "sonuç", zhs: "结果" },

  // Detail page sections
  "Merchant Price":  { eng: "Merchant Price", deu: "Händlerpreis", esp: "Precio del mercader", fra: "Prix du marchand", ita: "Prezzo del mercante", jpn: "商人の価格", kor: "상인 가격", pol: "Cena kupca", ptb: "Preço do mercador", rus: "Цена торговца", spa: "Precio del mercader", tha: "ราคาพ่อค้า", tur: "Tüccar Fiyatı", zhs: "商人价格" },
  "Powers Applied":  { eng: "Powers Applied", deu: "Angewandte Kräfte", esp: "Poderes aplicados", fra: "Pouvoirs appliqués", ita: "Poteri applicati", jpn: "適用パワー", kor: "적용 파워", pol: "Zastosowane moce", ptb: "Poderes aplicados", rus: "Применяемые силы", spa: "Poderes aplicados", tha: "พลังที่ใช้", tur: "Uygulanan Güçler", zhs: "应用能力" },
  "Related Cards":   { eng: "Related Cards", deu: "Verwandte Karten", esp: "Cartas relacionadas", fra: "Cartes liées", ita: "Carte correlate", jpn: "関連カード", kor: "관련 카드", pol: "Powiązane karty", ptb: "Cartas relacionadas", rus: "Связанные карты", spa: "Cartas relacionadas", tha: "การ์ดที่เกี่ยวข้อง", tur: "İlgili Kartlar", zhs: "相关卡牌" },
  "Other languages": { eng: "Other languages", deu: "Andere Sprachen", esp: "Otros idiomas", fra: "Autres langues", ita: "Altre lingue", jpn: "他の言語", kor: "다른 언어", pol: "Inne języki", ptb: "Outros idiomas", rus: "Другие языки", spa: "Otros idiomas", tha: "ภาษาอื่น", tur: "Diğer Diller", zhs: "其他语言" },
  "Version History": { eng: "Version History", deu: "Versionsgeschichte", esp: "Historial de versiones", fra: "Historique des versions", ita: "Cronologia versioni", jpn: "バージョン履歴", kor: "버전 기록", pol: "Historia wersji", ptb: "Histórico de versões", rus: "История версий", spa: "Historial de versiones", tha: "ประวัติเวอร์ชัน", tur: "Sürüm Geçmişi", zhs: "版本历史" },
  "Gold":            { eng: "Gold", deu: "Gold", esp: "Oro", fra: "Or", ita: "Oro", jpn: "ゴールド", kor: "골드", pol: "Złoto", ptb: "Ouro", rus: "Золото", spa: "Oro", tha: "ทอง", tur: "Altın", zhs: "金币" },
  "Cards":           { eng: "Cards", deu: "Karten", esp: "Cartas", fra: "Cartes", ita: "Carte", jpn: "カード", kor: "카드", pol: "Karty", ptb: "Cartas", rus: "Карты", spa: "Cartas", tha: "การ์ด", tur: "Kartlar", zhs: "卡牌" },
  "Relics":          { eng: "Relics", deu: "Relikte", esp: "Reliquias", fra: "Reliques", ita: "Reliquie", jpn: "レリック", kor: "유물", pol: "Relikty", ptb: "Relíquias", rus: "Реликвии", spa: "Reliquias", tha: "เรลิก", tur: "Kalıntılar", zhs: "遗物" },
  "Potions":         { eng: "Potions", deu: "Tränke", esp: "Pociones", fra: "Potions", ita: "Pozioni", jpn: "ポーション", kor: "물약", pol: "Mikstury", ptb: "Poções", rus: "Зелья", spa: "Pociones", tha: "ยา", tur: "İksirler", zhs: "药水" },
  "Monsters":        { eng: "Monsters", deu: "Monster", esp: "Monstruos", fra: "Monstres", ita: "Mostri", jpn: "モンスター", kor: "몬스터", pol: "Potwory", ptb: "Monstros", rus: "Монстры", spa: "Monstruos", tha: "มอนสเตอร์", tur: "Canavarlar", zhs: "怪物" },
  "Powers":          { eng: "Powers", deu: "Kräfte", esp: "Poderes", fra: "Pouvoirs", ita: "Poteri", jpn: "パワー", kor: "파워", pol: "Moce", ptb: "Poderes", rus: "Силы", spa: "Poderes", tha: "พลัง", tur: "Güçler", zhs: "能力" },
  "Events":          { eng: "Events", deu: "Ereignisse", esp: "Eventos", fra: "Événements", ita: "Eventi", jpn: "イベント", kor: "이벤트", pol: "Wydarzenia", ptb: "Eventos", rus: "События", spa: "Eventos", tha: "อีเวนต์", tur: "Etkinlikler", zhs: "事件" },
  "Characters":      { eng: "Characters", deu: "Charaktere", esp: "Personajes", fra: "Personnages", ita: "Personaggi", jpn: "キャラクター", kor: "캐릭터", pol: "Postacie", ptb: "Personagens", rus: "Персонажи", spa: "Personajes", tha: "ตัวละคร", tur: "Karakterler", zhs: "角色" },
  "Encounters":      { eng: "Encounters", deu: "Begegnungen", esp: "Encuentros", fra: "Rencontres", ita: "Incontri", jpn: "エンカウンター", kor: "조우", pol: "Spotkania", ptb: "Encontros", rus: "Встречи", spa: "Encuentros", tha: "การเผชิญหน้า", tur: "Karşılaşmalar", zhs: "遭遇" },
  "Enchantments":    { eng: "Enchantments", deu: "Verzauberungen", esp: "Encantamientos", fra: "Enchantements", ita: "Incantesimi", jpn: "エンチャント", kor: "인챈트", pol: "Zaklęcia", ptb: "Encantamentos", rus: "Зачарования", spa: "Encantamientos", tha: "มนตร์", tur: "Büyüler", zhs: "附魔" },

  // Sort
  "Compendium":      { eng: "Compendium", deu: "Kompendium", esp: "Compendio", fra: "Compendium", ita: "Compendio", jpn: "図鑑順", kor: "도감", pol: "Kompendium", ptb: "Compêndio", rus: "Компендиум", spa: "Compendio", tha: "สารานุกรม", tur: "Ansiklopedi", zhs: "图鉴" },

  // Nav groups
  "Database":        { eng: "Database", deu: "Datenbank", esp: "Base de datos", fra: "Base de données", ita: "Database", jpn: "データベース", kor: "데이터베이스", pol: "Baza danych", ptb: "Banco de dados", rus: "База данных", spa: "Base de datos", tha: "ฐานข้อมูล", tur: "Veritabanı", zhs: "数据库" },
  "Game Info":       { eng: "Game Info", deu: "Spielinfo", esp: "Info del juego", fra: "Info du jeu", ita: "Info gioco", jpn: "ゲーム情報", kor: "게임 정보", pol: "Info o grze", ptb: "Info do jogo", rus: "Инфо об игре", spa: "Info del juego", tha: "ข้อมูลเกม", tur: "Oyun Bilgisi", zhs: "游戏信息" },
  "About the Site":  { eng: "About the Site", deu: "Über die Seite", esp: "Sobre el sitio", fra: "À propos du site", ita: "Info sul sito", jpn: "サイトについて", kor: "사이트 정보", pol: "O stronie", ptb: "Sobre o site", rus: "О сайте", spa: "Sobre el sitio", tha: "เกี่ยวกับเว็บ", tur: "Site Hakkında", zhs: "关于本站" },

  // Nav link labels
  "Card Library":    { eng: "Card Library", deu: "Kartenbibliothek", esp: "Biblioteca de cartas", fra: "Bibliothèque de cartes", ita: "Libreria carte", jpn: "カードライブラリ", kor: "카드 도서관", pol: "Biblioteka kart", ptb: "Biblioteca de cartas", rus: "Библиотека карт", spa: "Biblioteca de cartas", tha: "คลังการ์ด", tur: "Kart Kütüphanesi", zhs: "卡牌库" },
  "Relic Collection": { eng: "Relic Collection", deu: "Reliktsammlung", esp: "Colección de reliquias", fra: "Collection de reliques", ita: "Collezione reliquie", jpn: "レリックコレクション", kor: "유물 컬렉션", pol: "Kolekcja reliktów", ptb: "Coleção de relíquias", rus: "Коллекция реликвий", spa: "Colección de reliquias", tha: "คอลเลกชันเรลิก", tur: "Kalıntı Koleksiyonu", zhs: "遗物收藏" },
  "Bestiary":        { eng: "Bestiary", deu: "Bestiarium", esp: "Bestiario", fra: "Bestiaire", ita: "Bestiario", jpn: "図鑑", kor: "도감", pol: "Bestiariusz", ptb: "Bestiário", rus: "Бестиарий", spa: "Bestiario", tha: "สัตว์ประหลาด", tur: "Yaratık Ansiklopedisi", zhs: "怪物图鉴" },
  "Potion Lab":      { eng: "Potion Lab", deu: "Trankküche", esp: "Laboratorio de pociones", fra: "Laboratoire de potions", ita: "Laboratorio pozioni", jpn: "ポーション工房", kor: "물약 연구소", pol: "Laboratorium mikstur", ptb: "Laboratório de poções", rus: "Лаборатория зелий", spa: "Laboratorio de pociones", tha: "ห้องปฏิบัติการยา", tur: "İksir Laboratuvarı", zhs: "药水实验室" },
  "Merchant":        { eng: "Merchant", deu: "Händler", esp: "Mercader", fra: "Marchand", ita: "Mercante", jpn: "商人", kor: "상인", pol: "Kupiec", ptb: "Mercador", rus: "Торговец", spa: "Mercader", tha: "พ่อค้า", tur: "Tüccar", zhs: "商人" },
  "Keywords":        { eng: "Keywords", deu: "Schlüsselwörter", esp: "Palabras clave", fra: "Mots-clés", ita: "Parole chiave", jpn: "キーワード", kor: "키워드", pol: "Słowa kluczowe", ptb: "Palavras-chave", rus: "Ключевые слова", spa: "Palabras clave", tha: "คีย์เวิร์ด", tur: "Anahtar Kelimeler", zhs: "关键词" },
  "Compare":         { eng: "Compare", deu: "Vergleichen", esp: "Comparar", fra: "Comparer", ita: "Confronta", jpn: "比較", kor: "비교", pol: "Porównaj", ptb: "Comparar", rus: "Сравнить", spa: "Comparar", tha: "เปรียบเทียบ", tur: "Karşılaştır", zhs: "比较" },
  "Timeline":        { eng: "Timeline", deu: "Zeitleiste", esp: "Línea de tiempo", fra: "Chronologie", ita: "Cronologia", jpn: "タイムライン", kor: "타임라인", pol: "Oś czasu", ptb: "Linha do tempo", rus: "Хронология", spa: "Línea de tiempo", tha: "ไทม์ไลน์", tur: "Zaman Çizelgesi", zhs: "时间线" },
  "Images":          { eng: "Images", deu: "Bilder", esp: "Imágenes", fra: "Images", ita: "Immagini", jpn: "画像", kor: "이미지", pol: "Obrazy", ptb: "Imagens", rus: "Изображения", spa: "Imágenes", tha: "รูปภาพ", tur: "Görseller", zhs: "图片" },
  "Reference":       { eng: "Reference", deu: "Referenz", esp: "Referencia", fra: "Référence", ita: "Riferimento", jpn: "リファレンス", kor: "레퍼런스", pol: "Referencja", ptb: "Referência", rus: "Справочник", spa: "Referencia", tha: "อ้างอิง", tur: "Referans", zhs: "参考" },
  "Showcase":        { eng: "Showcase", deu: "Galerie", esp: "Galería", fra: "Vitrine", ita: "Vetrina", jpn: "ショーケース", kor: "쇼케이스", pol: "Prezentacja", ptb: "Vitrine", rus: "Витрина", spa: "Galería", tha: "โชว์เคส", tur: "Vitrin", zhs: "展示" },
  "Changelog":       { eng: "Changelog", deu: "Änderungsprotokoll", esp: "Registro de cambios", fra: "Journal des modifications", ita: "Registro modifiche", jpn: "変更履歴", kor: "변경 이력", pol: "Dziennik zmian", ptb: "Registro de alterações", rus: "Журнал изменений", spa: "Registro de cambios", tha: "บันทึกการเปลี่ยนแปลง", tur: "Değişiklik Günlüğü", zhs: "更新日志" },
  "About":           { eng: "About", deu: "Über", esp: "Acerca de", fra: "À propos", ita: "Info", jpn: "概要", kor: "소개", pol: "O nas", ptb: "Sobre", rus: "О проекте", spa: "Acerca de", tha: "เกี่ยวกับ", tur: "Hakkında", zhs: "关于" },
  "Developers":      { eng: "Developers", deu: "Entwickler", esp: "Desarrolladores", fra: "Développeurs", ita: "Sviluppatori", jpn: "開発者", kor: "개발자", pol: "Deweloperzy", ptb: "Desenvolvedores", rus: "Разработчики", spa: "Desarrolladores", tha: "นักพัฒนา", tur: "Geliştiriciler", zhs: "开发者" },
  "Discord":         { eng: "Discord", deu: "Discord", esp: "Discord", fra: "Discord", ita: "Discord", jpn: "Discord", kor: "Discord", pol: "Discord", ptb: "Discord", rus: "Discord", spa: "Discord", tha: "Discord", tur: "Discord", zhs: "Discord" },

  // Misc
  "Share":           { eng: "Share", deu: "Teilen", esp: "Compartir", fra: "Partager", ita: "Condividi", jpn: "共有", kor: "공유", pol: "Udostępnij", ptb: "Compartilhar", rus: "Поделиться", spa: "Compartir", tha: "แชร์", tur: "Paylaş", zhs: "分享" },
  "Loading...":      { eng: "Loading...", deu: "Laden...", esp: "Cargando...", fra: "Chargement...", ita: "Caricamento...", jpn: "読み込み中...", kor: "로딩...", pol: "Ładowanie...", ptb: "Carregando...", rus: "Загрузка...", spa: "Cargando...", tha: "กำลังโหลด...", tur: "Yükleniyor...", zhs: "加载中..." },
  "Not Found":       { eng: "Not Found", deu: "Nicht gefunden", esp: "No encontrado", fra: "Non trouvé", ita: "Non trovato", jpn: "見つかりません", kor: "찾을 수 없음", pol: "Nie znaleziono", ptb: "Não encontrado", rus: "Не найдено", spa: "No encontrado", tha: "ไม่พบ", tur: "Bulunamadı", zhs: "未找到" },
  "Damage Values":   { eng: "Damage Values", deu: "Schadenswerte", esp: "Valores de daño", fra: "Valeurs de dégâts", ita: "Valori di danno", jpn: "ダメージ値", kor: "데미지 수치", pol: "Wartości obrażeń", ptb: "Valores de dano", rus: "Значения урона", spa: "Valores de daño", tha: "ค่าความเสียหาย", tur: "Hasar Değerleri", zhs: "伤害值" },
  "Block Values":    { eng: "Block Values", deu: "Blockwerte", esp: "Valores de bloqueo", fra: "Valeurs de blocage", ita: "Valori di blocco", jpn: "ブロック値", kor: "방어 수치", pol: "Wartości bloku", ptb: "Valores de bloqueio", rus: "Значения блока", spa: "Valores de bloqueo", tha: "ค่าป้องกัน", tur: "Blok Değerleri", zhs: "格挡值" },
  "Moves":           { eng: "Moves", deu: "Züge", esp: "Movimientos", fra: "Coups", ita: "Mosse", jpn: "ムーブ", kor: "행동", pol: "Ruchy", ptb: "Movimentos", rus: "Ходы", spa: "Movimientos", tha: "การเคลื่อนไหว", tur: "Hamleler", zhs: "招式" },

  // Page taglines / descriptions
  "cards_tagline": { eng: "Browse every card across Ironclad, Silent, Defect, Necrobinder, and Regent. Filter by character, type, rarity, and keywords.", deu: "Alle Karten durchsuchen — Ironclad, Silent, Defect, Necrobinder und Regent. Filtern nach Charakter, Typ, Seltenheit und Schlüsselwörtern.", esp: "Explora todas las cartas de Ironclad, Silent, Defect, Necrobinder y Regent. Filtra por personaje, tipo, rareza y palabras clave.", fra: "Parcourez toutes les cartes d'Ironclad, Silent, Defect, Necrobinder et Regent. Filtrez par personnage, type, rareté et mots-clés.", ita: "Sfoglia tutte le carte di Ironclad, Silent, Defect, Necrobinder e Regent. Filtra per personaggio, tipo, rarità e parole chiave.", jpn: "アイアンクラッド、サイレント、ディフェクト、ネクロバインダー、リージェントの全カードを閲覧。キャラクター、タイプ、レアリティ、キーワードでフィルター。", kor: "아이언클래드, 사일런트, 디펙트, 네크로바인더, 리전트의 모든 카드를 탐색하세요. 캐릭터, 유형, 희귀도, 키워드로 필터링.", pol: "Przeglądaj wszystkie karty Ironclada, Silent, Defecta, Necrobindera i Regenta. Filtruj według postaci, typu, rzadkości i słów kluczowych.", ptb: "Navegue por todas as cartas de Ironclad, Silent, Defect, Necrobinder e Regent. Filtre por personagem, tipo, raridade e palavras-chave.", rus: "Просмотрите все карты Ironclad, Silent, Defect, Necrobinder и Regent. Фильтруйте по персонажу, типу, редкости и ключевым словам.", spa: "Explora todas las cartas de Ironclad, Silent, Defect, Necrobinder y Regent. Filtra por personaje, tipo, rareza y palabras clave.", tha: "เรียกดูการ์ดทั้งหมดของ Ironclad, Silent, Defect, Necrobinder และ Regent กรองตามตัวละคร ประเภท ความหายาก และคีย์เวิร์ด", tur: "Ironclad, Silent, Defect, Necrobinder ve Regent'ın tüm kartlarını inceleyin. Karakter, tür, nadirlik ve anahtar kelimelere göre filtreleyin.", zhs: "浏览铁甲战士、沉默猎手、缺陷体、亡灵师、摄政王的所有卡牌。按角色、类型、稀有度和关键词筛选。" },
  "relics_tagline": { eng: "Browse every relic across all rarities and character pools. Filter by rarity and pool.", deu: "Alle Relikte aller Seltenheiten und Charakterpools durchsuchen. Nach Seltenheit und Pool filtern.", esp: "Explora todas las reliquias de todas las rarezas y grupos de personajes. Filtra por rareza y grupo.", fra: "Parcourez toutes les reliques de toutes les raretés et groupes de personnages. Filtrez par rareté et groupe.", ita: "Sfoglia tutte le reliquie di ogni rarità e gruppo di personaggi. Filtra per rarità e gruppo.", jpn: "全レアリティ・全キャラクタープールのレリックを閲覧。レアリティとプールでフィルター。", kor: "모든 희귀도와 캐릭터 풀의 유물을 탐색하세요. 희귀도와 풀로 필터링.", pol: "Przeglądaj wszystkie relikty wszystkich rzadkości i pul postaci. Filtruj według rzadkości i puli.", ptb: "Navegue por todas as relíquias de todas as raridades e grupos de personagens. Filtre por raridade e grupo.", rus: "Просмотрите все реликвии всех редкостей и пулов персонажей. Фильтруйте по редкости и пулу.", spa: "Explora todas las reliquias de todas las rarezas y grupos de personajes. Filtra por rareza y grupo.", tha: "เรียกดูเรลิกทั้งหมดทุกความหายากและกลุ่มตัวละคร กรองตามความหายากและกลุ่ม", tur: "Tüm nadirlik ve karakter havuzlarındaki kalıntıları inceleyin. Nadirlik ve havuza göre filtreleyin.", zhs: "浏览所有稀有度和角色池的遗物。按稀有度和池筛选。" },
  "potions_tagline": { eng: "Browse every potion. Filter by rarity and character pool.", deu: "Alle Tränke durchsuchen. Nach Seltenheit und Charakterpool filtern.", esp: "Explora todas las pociones. Filtra por rareza y grupo de personajes.", fra: "Parcourez toutes les potions. Filtrez par rareté et groupe de personnages.", ita: "Sfoglia tutte le pozioni. Filtra per rarità e gruppo di personaggi.", jpn: "全ポーションを閲覧。レアリティとキャラクタープールでフィルター。", kor: "모든 물약을 탐색하세요. 희귀도와 캐릭터 풀로 필터링.", pol: "Przeglądaj wszystkie mikstury. Filtruj według rzadkości i puli postaci.", ptb: "Navegue por todas as poções. Filtre por raridade e grupo de personagens.", rus: "Просмотрите все зелья. Фильтруйте по редкости и пулу персонажей.", spa: "Explora todas las pociones. Filtra por rareza y grupo de personajes.", tha: "เรียกดูยาทั้งหมด กรองตามความหายากและกลุ่มตัวละคร", tur: "Tüm iksirleri inceleyin. Nadirlik ve karakter havuzuna göre filtreleyin.", zhs: "浏览所有药水。按稀有度和角色池筛选。" },
  "monsters_tagline": { eng: "Browse every monster — normals, elites, and bosses. View HP values, moves, damage stats, and ascension scaling.", deu: "Alle Monster durchsuchen — Normale, Eliten und Bosse. HP-Werte, Züge, Schadenswerte und Aufstiegsskalierung ansehen.", esp: "Explora todos los monstruos — normales, élites y jefes. Consulta HP, movimientos, daño y escalado de ascensión.", fra: "Parcourez tous les monstres — normaux, élites et boss. Consultez les PV, coups, dégâts et la progression d'ascension.", ita: "Sfoglia tutti i mostri — normali, élite e boss. Visualizza HP, mosse, danni e scalatura ascensione.", jpn: "全モンスターを閲覧 — ノーマル、エリート、ボス。HP、ムーブ、ダメージ、アセンション補正を確認。", kor: "모든 몬스터 탐색 — 일반, 엘리트, 보스. HP, 행동, 데미지, 승천 스케일링 확인.", pol: "Przeglądaj wszystkie potwory — zwykłe, elitarne i bossów. Sprawdź HP, ruchy, obrażenia i skalowanie ascensji.", ptb: "Navegue por todos os monstros — normais, elites e chefes. Veja HP, movimentos, dano e escalonamento de ascensão.", rus: "Просмотрите всех монстров — обычных, элитных и боссов. HP, ходы, урон и масштабирование восхождения.", spa: "Explora todos los monstruos — normales, élites y jefes. Consulta HP, movimientos, daño y escalado de ascensión.", tha: "เรียกดูมอนสเตอร์ทั้งหมด — ปกติ อีลิท และบอส ดู HP การเคลื่อนไหว ค่าความเสียหาย และ Ascension", tur: "Tüm canavarları inceleyin — normal, elit ve boss. HP, hamleler, hasar ve tırmanma ölçeklendirmesini görüntüleyin.", zhs: "浏览所有怪物 — 普通、精英和Boss。查看HP、招式、伤害和登塔缩放。" },
  "powers_tagline": { eng: "Browse every power — buffs, debuffs, and neutral effects. Filter by type and stack behavior.", deu: "Alle Kräfte durchsuchen — Buffs, Debuffs und neutrale Effekte. Nach Typ und Stapelverhalten filtern.", esp: "Explora todos los poderes — mejoras, debilitaciones y efectos neutrales. Filtra por tipo y comportamiento de acumulación.", fra: "Parcourez tous les pouvoirs — améliorations, affaiblissements et effets neutres. Filtrez par type et comportement d'empilement.", ita: "Sfoglia tutti i poteri — buff, debuff ed effetti neutrali. Filtra per tipo e comportamento di accumulo.", jpn: "全パワーを閲覧 — バフ、デバフ、中立効果。タイプとスタック動作でフィルター。", kor: "모든 파워 탐색 — 버프, 디버프, 중립 효과. 유형과 스택 동작으로 필터링.", pol: "Przeglądaj wszystkie moce — buffy, debuffy i efekty neutralne. Filtruj według typu i zachowania stosu.", ptb: "Navegue por todos os poderes — buffs, debuffs e efeitos neutros. Filtre por tipo e comportamento de acúmulo.", rus: "Просмотрите все силы — баффы, дебаффы и нейтральные эффекты. Фильтруйте по типу и поведению стака.", spa: "Explora todos los poderes — mejoras, debilitaciones y efectos neutrales. Filtra por tipo y acumulación.", tha: "เรียกดูพลังทั้งหมด — บัฟ ดีบัฟ และเอฟเฟกต์กลาง กรองตามประเภทและพฤติกรรมสแต็ก", tur: "Tüm güçleri inceleyin — buff, debuff ve nötr etkiler. Tür ve yığılma davranışına göre filtreleyin.", zhs: "浏览所有能力 — 增益、减益和中性效果。按类型和叠加行为筛选。" },
  "events_tagline": { eng: "Browse every event including shrine events, Ancient encounters, and story events. View choices, dialogue, and outcomes.", deu: "Alle Ereignisse durchsuchen — Schrein-Ereignisse, Uralte Begegnungen und Story-Ereignisse. Entscheidungen, Dialoge und Ergebnisse ansehen.", esp: "Explora todos los eventos incluidos santuarios, encuentros ancestrales y eventos de historia. Consulta decisiones, diálogos y resultados.", fra: "Parcourez tous les événements — sanctuaires, rencontres ancestrales et événements d'histoire. Consultez les choix, dialogues et résultats.", ita: "Sfoglia tutti gli eventi — santuari, incontri ancestrali ed eventi della storia. Visualizza scelte, dialoghi e risultati.", jpn: "全イベントを閲覧 — 祠イベント、エンシェント遭遇、ストーリーイベント。選択肢、対話、結果を確認。", kor: "모든 이벤트 탐색 — 제단 이벤트, 고대 조우, 스토리 이벤트. 선택지, 대화, 결과 확인.", pol: "Przeglądaj wszystkie wydarzenia — sanktuaria, pradawne spotkania i wydarzenia fabularne. Sprawdź wybory, dialogi i wyniki.", ptb: "Navegue por todos os eventos — santuários, encontros ancestrais e eventos de história. Veja escolhas, diálogos e resultados.", rus: "Просмотрите все события — святилища, встречи с Древними и сюжетные события. Выборы, диалоги и исходы.", spa: "Explora todos los eventos — santuarios, encuentros ancestrales y eventos de historia. Consulta decisiones, diálogos y resultados.", tha: "เรียกดูอีเวนต์ทั้งหมด — ศาลเจ้า การเผชิญหน้าโบราณ และอีเวนต์เรื่องราว ดูทางเลือก บทสนทนา และผลลัพธ์", tur: "Tüm etkinlikleri inceleyin — tapınak, Kadim karşılaşmalar ve hikaye etkinlikleri. Seçenekleri, diyalogları ve sonuçları görüntüleyin.", zhs: "浏览所有事件 — 神龛事件、远古遭遇和故事事件。查看选择、对话和结果。" },
  "characters_tagline": { eng: "All playable characters — view starting decks, relics, HP, gold, energy, and more.", deu: "Alle spielbaren Charaktere — Startdecks, Relikte, HP, Gold, Energie und mehr.", esp: "Todos los personajes jugables — mazos iniciales, reliquias, HP, oro, energía y más.", fra: "Tous les personnages jouables — decks de départ, reliques, PV, or, énergie et plus.", ita: "Tutti i personaggi giocabili — deck iniziali, reliquie, HP, oro, energia e altro.", jpn: "全プレイアブルキャラクター — 初期デッキ、レリック、HP、ゴールド、エネルギーなど。", kor: "모든 플레이어블 캐릭터 — 시작 덱, 유물, HP, 골드, 에너지 등.", pol: "Wszystkie grywalne postacie — startowe talie, relikty, HP, złoto, energia i więcej.", ptb: "Todos os personagens jogáveis — decks iniciais, relíquias, HP, ouro, energia e mais.", rus: "Все игровые персонажи — стартовые колоды, реликвии, HP, золото, энергия и другое.", spa: "Todos los personajes jugables — mazos iniciales, reliquias, HP, oro, energía y más.", tha: "ตัวละครที่เล่นได้ทั้งหมด — เด็คเริ่มต้น เรลิก HP ทอง พลังงาน และอื่นๆ", tur: "Tüm oynanabilir karakterler — başlangıç desteleri, kalıntılar, HP, altın, enerji ve daha fazlası.", zhs: "所有可玩角色 — 初始牌组、遗物、HP、金币、能量等。" },
  "encounters_tagline": { eng: "Browse every combat encounter. Filter by room type and act.", deu: "Alle Kampfbegegnungen durchsuchen. Nach Raumtyp und Akt filtern.", esp: "Explora todos los encuentros de combate. Filtra por tipo de sala y acto.", fra: "Parcourez toutes les rencontres de combat. Filtrez par type de salle et acte.", ita: "Sfoglia tutti gli scontri di combattimento. Filtra per tipo di stanza e atto.", jpn: "全戦闘エンカウンターを閲覧。部屋タイプとアクトでフィルター。", kor: "모든 전투 조우를 탐색하세요. 방 유형과 막으로 필터링.", pol: "Przeglądaj wszystkie spotkania bojowe. Filtruj według typu pokoju i aktu.", ptb: "Navegue por todos os encontros de combate. Filtre por tipo de sala e ato.", rus: "Просмотрите все боевые встречи. Фильтруйте по типу комнаты и акту.", spa: "Explora todos los encuentros de combate. Filtra por tipo de sala y acto.", tha: "เรียกดูการเผชิญหน้าการต่อสู้ทั้งหมด กรองตามประเภทห้องและฉาก", tur: "Tüm savaş karşılaşmalarını inceleyin. Oda türü ve perdeye göre filtreleyin.", zhs: "浏览所有战斗遭遇。按房间类型和幕筛选。" },
  "enchantments_tagline": { eng: "Browse every enchantment. Filter by card type and view effects, stackability, and extra card text.", deu: "Alle Verzauberungen durchsuchen. Nach Kartentyp filtern und Effekte, Stapelbarkeit und zusätzlichen Kartentext ansehen.", esp: "Explora todos los encantamientos. Filtra por tipo de carta y consulta efectos, acumulabilidad y texto adicional.", fra: "Parcourez tous les enchantements. Filtrez par type de carte et consultez les effets, l'empilabilité et le texte supplémentaire.", ita: "Sfoglia tutti gli incantesimi. Filtra per tipo di carta e visualizza effetti, accumulabilità e testo aggiuntivo.", jpn: "全エンチャントを閲覧。カードタイプでフィルターし、効果、重複可否、追加テキストを確認。", kor: "모든 인챈트를 탐색하세요. 카드 유형으로 필터링하고 효과, 중첩 가능 여부, 추가 텍스트를 확인.", pol: "Przeglądaj wszystkie zaklęcia. Filtruj według typu karty i sprawdź efekty, możliwość stosowania i dodatkowy tekst.", ptb: "Navegue por todos os encantamentos. Filtre por tipo de carta e veja efeitos, acumulabilidade e texto adicional.", rus: "Просмотрите все зачарования. Фильтруйте по типу карты и просматривайте эффекты, складываемость и доп. текст.", spa: "Explora todos los encantamientos. Filtra por tipo de carta y consulta efectos, acumulabilidad y texto adicional.", tha: "เรียกดูมนตร์ทั้งหมด กรองตามประเภทการ์ดและดูเอฟเฟกต์ การซ้อน และข้อความเพิ่มเติม", tur: "Tüm büyüleri inceleyin. Kart türüne göre filtreleyin ve etkileri, yığılabilirliği ve ek kart metnini görüntüleyin.", zhs: "浏览所有附魔。按卡牌类型筛选，查看效果、可叠加性和额外文本。" },
};

/**
 * Get a translated UI string.
 * Keys are the English display text (e.g., "Back to", "Overview").
 */
export function t(key: string, lang: string): string {
  const entry = UI[key];
  if (!entry) return key;
  return entry[lang] || entry.eng || key;
}
